import { SituationTemplate } from '@/types'

export const SITUATION_TEMPLATES: SituationTemplate[] = [
  // === 일상 루틴 ===
  {
    id: 'morning_work',
    name: '출근 준비',
    description: '깜빡하기 쉬운 출근 필수템들',
    category: '일상',
    peopleMultiplier: false,
    items: [
      { title: '지갑', description: '신용카드, 현금, 신분증', baseQuantity: 1, unit: '개' },
      { title: '교통카드', description: '지하철/버스 카드', baseQuantity: 1, unit: '개' },
      { title: '회사 출입카드', description: '사원증/출입카드', baseQuantity: 1, unit: '개' },
      { title: '핸드폰', description: '충전 확인', baseQuantity: 1, unit: '개' },
      { title: '이어폰', description: '무선/유선 이어폰', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '개인 방역용', baseQuantity: 2, unit: '개' },
      { title: '우산', description: '날씨 확인 후', baseQuantity: 1, unit: '개' },
      { title: '텀블러', description: '카페 할인 + 환경보호', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '오후 허기 대비', baseQuantity: 1, unit: '개' },
      { title: '충전기', description: '휴대용 보조배터리', baseQuantity: 1, unit: '개' },
      { title: '월급날까지 D-day 계산', description: '😂 정신적 지탱을 위한 필수 확인사항', baseQuantity: 1, unit: '회' },
      { title: '엘리베이터 버튼 누르기 경쟁 준비', description: '🏃‍♂️ 아침 출근 러시아워 생존템', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'gym_prep',
    name: '헬스장 준비',
    description: '운동 효과 극대화 준비물',
    category: '운동',
    peopleMultiplier: false,
    items: [
      { title: '운동복', description: '통기성 좋은 셔츠+반바지', baseQuantity: 1, unit: '벌' },
      { title: '운동화', description: '웨이트 전용 신발', baseQuantity: 1, unit: '켤레' },
      { title: '수건', description: '개인 수건 (대형)', baseQuantity: 1, unit: '개' },
      { title: '물병', description: '1L 이상 대용량', baseQuantity: 1, unit: '개' },
      { title: '헬스장 멤버십', description: '출입용 카드/앱', baseQuantity: 1, unit: '개' },
      { title: '운동장갑', description: '웨이트 트레이닝용', baseQuantity: 1, unit: '개' },
      { title: '이어폰', description: '운동 음악용', baseQuantity: 1, unit: '개' },
      { title: '프로틴', description: '운동 후 단백질', baseQuantity: 1, unit: '개' },
      { title: '개인물품보관함', description: '휴대폰, 지갑 보관용 파우치', baseQuantity: 1, unit: '개' },
      { title: '샤워용품', description: '샴푸, 바디워시', baseQuantity: 1, unit: '세트' },
      { title: '손목보호대', description: '🔥꿀팁: 벤치프레스/프레스 필수', baseQuantity: 1, unit: '개' },
      { title: '팔꿈치 보호대', description: '🔥꿀팁: 테니스엘보우 예방', baseQuantity: 1, unit: '개' },
      { title: '고중량용 복압벨트', description: '🔥꿀팁: 데드리프트/스쿼트 안전', baseQuantity: 1, unit: '개' },
      { title: '무릎보호대', description: '🔥꿀팁: 스쿼트/런지 무릎보호', baseQuantity: 1, unit: '개' },
      { title: '운동 플레이리스트', description: '🎵 \"아이 캔 플라이\" 같은 동기부여 음악 필수', baseQuantity: 1, unit: '세트' },
      { title: '거울 앞 포즈 연습', description: '💪 운동 전 자신감 충전용 (선택사항)', baseQuantity: 1, unit: '회' },
    ]
  },
  {
    id: 'before_sleep',
    name: '잠자기 전',
    description: '숙면과 내일 준비를 위한 체크',
    category: '일상',
    peopleMultiplier: false,
    items: [
      { title: '핸드폰 충전', description: '침대 옆 충전케이블', baseQuantity: 1, unit: '개' },
      { title: '알람 설정', description: '기상 시간 + 여유 5분', baseQuantity: 1, unit: '개' },
      { title: '내일 옷 준비', description: '날씨 확인 후 의상', baseQuantity: 1, unit: '벌' },
      { title: '현관문 잠금', description: '도어락/열쇠 확인', baseQuantity: 1, unit: '회' },
      { title: '가스밸브 잠금', description: '안전 확인', baseQuantity: 1, unit: '회' },
      { title: '창문 닫기', description: '방범/온도 조절', baseQuantity: 1, unit: '회' },
      { title: '내일 일정 확인', description: '캘린더/메모 점검', baseQuantity: 1, unit: '회' },
      { title: '물 한잔', description: '숙면을 위한 수분 보충', baseQuantity: 1, unit: '잔' },
    ]
  },
  {
    id: 'camping',
    name: '캠핑',
    description: '캠핑에 필요한 기본 준비물',
    category: '아웃도어',
    peopleMultiplier: true,
    items: [
      { title: '텐트', description: '🏕️ 방수 기능이 있는 텐트', baseQuantity: 1, unit: '개' },
      { title: '침낭', description: '🛏️ 계절에 맞는 침낭', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '매트', description: '바닥 매트', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '블루투스 스피커', description: '🎵 캠핑 필수템! 분위기 UP', baseQuantity: 1, unit: '개' },
      { title: '보조배터리', description: '🔋 20000mAh 이상, 핸드폰 충전용', baseQuantity: 1, unit: '개' },
      { title: '고기', description: '🥩 바베큐용 고기 (남성 300g, 여성 200g 평균)', baseQuantity: 250, unit: 'g', multiplier: 1 },
      { title: '쌈장', description: '🥄 고기용 쌈장 (8인까지 충분)', baseQuantity: 1, unit: '개' },
      { title: '상추/깻잎', description: '🥬 쌈 채소 (4인 기준)', baseQuantity: 2, unit: '봉지' },
      { title: '가위', description: '✂️ 고기용 가위', baseQuantity: 1, unit: '개' },
      { title: '집게', description: '바베큐 집게', baseQuantity: 2, unit: '개' },
      { title: '그릴', description: '바베큐 그릴', baseQuantity: 1, unit: '개' },
      { title: '숯', description: '바베큐용 숯', baseQuantity: 3, unit: 'kg' },
      { title: '착화제', description: '숯 점화용', baseQuantity: 1, unit: '개' },
      { title: '물', description: '💧 식수 (남성 1.3L, 여성 1.1L 평균)', baseQuantity: 1.2, unit: 'L', multiplier: 1 },
      { title: '랜턴', description: '🏮 LED 랜턴', baseQuantity: 1, unit: '개' },
      { title: '헤드랜턴', description: '개인용 헤드랜턴', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '모기 퇴치제', description: '🦟 여름 캠핑 필수템', baseQuantity: 1, unit: '개' },
      { title: '젖은 물티슈', description: '🧻 손 씻기 어려운 환경 (1박2일 기준)', baseQuantity: 1, unit: '팩' },
      { title: '캠핑 의자', description: '🪑 접이식 의자', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '아이스박스', description: '🧊 음료, 고기 보관용', baseQuantity: 1, unit: '개' },
      { title: '얼음', description: '🧊 아이스박스용', baseQuantity: 3, unit: 'kg' },
      { title: '캠핑용 슬리퍼', description: '😂 텐트 안에서만 신는 귀여운 슬리퍼', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '인증샷 소품', description: '📸 "나 캠핑왔다" 인증용 모자/선글라스', baseQuantity: 1, unit: '세트' },
      { title: '알루미늄 호일', description: '🔥꿀팁: 고기 포장지, 접시 대용, 보온 효과', baseQuantity: 1, unit: '개' },
      { title: '멀티툴', description: '🔥꿀팁: 캔따개, 칼, 가위 올인원', baseQuantity: 1, unit: '개' },
      { title: '방수 타프', description: '🔥꿀팁: 갑작스런 비 대비, 그늘막 겸용', baseQuantity: 1, unit: '개' },
      { title: '휴지+화장지', description: '🔥꿀팁: 자연 속 화장실용 필수템', baseQuantity: 4, unit: '롤' },
    ]
  },
  {
    id: 'pension',
    name: '펜션',
    description: '펜션 여행 준비물',
    category: '여행',
    peopleMultiplier: true,
    items: [
      { title: '수건', description: '개인용 수건', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '세면도구', description: '칫솔, 치약, 샴푸 등', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '슬리퍼', description: '개인용 슬리퍼', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '여벌 옷', description: '갈아입을 옷', baseQuantity: 2, unit: '벌', multiplier: 1 },
      { title: '간식', description: '🍪 함께 나눠먹을 간식 (과자, 과일 등)', baseQuantity: 5, unit: '개' },
      { title: '음료', description: '🥤 시원한 음료 (1인당 2개)', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '게임', description: '보드게임 또는 카드게임', baseQuantity: 2, unit: '개' },
      { title: '충전기', description: '휴대폰 충전기', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '"누워서 넷플릭스" 세트', description: '😴 침대+간식+드라마 완벽 조합', baseQuantity: 1, unit: '세트' },
      { title: '셀카봉', description: '📸 "펜션놀러왔다" 인증샷 필수템', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'interview',
    name: '면접',
    description: '면접 준비물',
    category: '업무',
    peopleMultiplier: false,
    items: [
      { title: '이력서', description: '인쇄된 이력서', baseQuantity: 3, unit: '부' },
      { title: '자기소개서', description: '인쇄된 자기소개서', baseQuantity: 3, unit: '부' },
      { title: '포트폴리오', description: '작업물 모음집', baseQuantity: 1, unit: '개' },
      { title: '신분증', description: '주민등록증 또는 운전면허증', baseQuantity: 1, unit: '개' },
      { title: '증명사진', description: '여분의 증명사진', baseQuantity: 2, unit: '매' },
      { title: '펜', description: '볼펜', baseQuantity: 2, unit: '개' },
      { title: '메모장', description: '작은 메모장', baseQuantity: 1, unit: '개' },
      { title: '시계', description: '시간 확인용', baseQuantity: 1, unit: '개' },
      { title: '면접관을 웃게 만들 준비된 농담', description: '😄 적절한 유머감각 어필 (단, 과용 금지)', baseQuantity: 1, unit: '개' },
      { title: '\"저 뽑으면 후회 안함\" 자신감', description: '💪 마인드 컨트롤 완료 체크', baseQuantity: 1, unit: '회' },
    ]
  },
  {
    id: 'hiking',
    name: '등산',
    description: '등산 준비물',
    category: '아웃도어',
    peopleMultiplier: true,
    items: [
      { title: '등산화', description: '미끄럼 방지 등산화', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '배낭', description: '등산용 배낭', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '등산복', description: '땀 배출이 잘 되는 옷', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '물', description: '💧 등산용 충분한 수분 (남성 1.8L, 여성 1.3L)', baseQuantity: 1.5, unit: 'L', multiplier: 1 },
      { title: '간식', description: '🍫 에너지바, 견과류 (남성 4개, 여성 2개)', baseQuantity: 3, unit: '개', multiplier: 1 },
      { title: '등산스틱', description: '트레킹 폴', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '모자', description: '햇빛 차단용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '선크림', description: 'SPF 50+', baseQuantity: 1, unit: '개' },
      { title: '구급약', description: '반창고, 소독약 등', baseQuantity: 1, unit: '세트' },
      { title: '목베개', description: '🔥꿀팁: 장거리 이동 필수', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '무릎 테이핑', description: '🔥꿀팁: 하산시 무릎 보호 필수템', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '전해질 음료', description: '🔥꿀팁: 물 + 포카리 조합으로 탈수 방지', baseQuantity: 2, unit: '개' },
      { title: '호루라기', description: '🔥꿀팁: 조난시 구조 신호용 생명템', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '아이마스크+귀마개', description: '🔥꿀팁: 숙면 도우미', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '여행용 슬리퍼', description: '🔥꿀팁: 숙소에서 편안하게', baseQuantity: 1, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'running',
    name: '러닝',
    description: '러닝 준비물',
    category: '운동',
    peopleMultiplier: false,
    items: [
      { title: '러닝화', description: '쿠셔닝이 좋은 러닝화', baseQuantity: 1, unit: '켤레' },
      { title: '러닝복', description: '통기성 좋은 운동복', baseQuantity: 1, unit: '벌' },
      { title: '물병', description: '수분 보충용', baseQuantity: 1, unit: '개' },
      { title: '스마트워치', description: '운동량 측정용', baseQuantity: 1, unit: '개' },
      { title: '이어폰', description: '무선 이어폰', baseQuantity: 1, unit: '개' },
      { title: '수건', description: '땀 닦기용 작은 수건', baseQuantity: 1, unit: '개' },
      { title: '휴대폰', description: '음악 재생 및 긴급상황 대비', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'southeast_asia',
    name: '동남아 여행',
    description: '🌴 동남아 특화 준비물 (현지 팁 포함)',
    category: '해외여행',
    peopleMultiplier: true,
    items: [
      { title: '여권', description: '유효기간 6개월 이상 필수', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '110V 어댑터', description: '⚡ 한국 220V와 다름! C타입/A타입', baseQuantity: 1, unit: '개' },
      { title: '방수 파우치', description: '📱 스콜(소나기) 대비, 핸드폰 필수', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '설사약', description: '💊 현지 음식 적응용 (정로환/스멕타)', baseQuantity: 1, unit: '박스' },
      { title: '모기 퇴치제', description: '🦟 열대 모기 강력함. DEET 성분', baseQuantity: 1, unit: '개' },
      { title: 'SPF50+ 선크림', description: '☀️ 적도 근처 자외선 강함', baseQuantity: 2, unit: '개' },
      { title: '속건 티셔츠', description: '👕 습도 90% 환경, 빨래 3일 안마름', baseQuantity: 3, unit: '개', multiplier: 1 },
      { title: '얇은 긴팔', description: '🧥 에어컨 너무 추움, 냉방병 주의', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '샌들', description: '👟 비 많음, 빨리 마르는 소재', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '현금 USD', description: '💵 카드 안되는 곳 많음, 달러 준비 (총 200불 정도)', baseQuantity: 200, unit: 'USD' },
      { title: '물티슈', description: '🧻 화장실 휴지 없는 곳 많음. 대형 팩으로!', baseQuantity: 3, unit: '팩' },
      { title: '해외여행보험', description: '🏥 의료비 비쌈, 필수 가입. 트리플에서 할인 혜택', baseQuantity: 1, unit: '개' },
      { title: '지퍼백', description: '🔥꿀팁: 젖은 옷, 더러운 옷 분리 보관', baseQuantity: 5, unit: '개' },
      { title: '스카프/목토시', description: '🔥꿀팁: 사원 입장시 어깨 가리기용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '정로환+락토핏', description: '🔥꿀팁: 설사 + 배탈 이중 대비', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'europe',
    name: '유럽 여행',
    description: '🏰 유럽 특화 준비물 (현지 팁 포함)',
    category: '해외여행',
    peopleMultiplier: true,
    items: [
      { title: '여권', description: '유효기간 6개월 이상 + 복사본', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '220V C타입 어댑터', description: '🔌 한국과 동일 전압, C타입 필수', baseQuantity: 1, unit: '개' },
      { title: '여행용 멀티탭', description: '⚡ 호텔 콘센트 부족, 멀티탭 필수', baseQuantity: 1, unit: '개' },
      { title: '현금 유로', description: '💶 팁 문화 있음, 소액권 준비 (총 300유로 정도)', baseQuantity: 300, unit: 'EUR' },
      { title: '체크카드', description: '💳 해외 수수료 낮은 카드', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '텀블러', description: '🥤 물값 비쌈(3-5유로), 텀블러 필수', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '걷기 편한 신발', description: '👟 하루 2만보 각오, 쿠셔닝 중요', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '레이어링 의류', description: '🧥 일교차 크고 변덕스러운 날씨', baseQuantity: 3, unit: '벌', multiplier: 1 },
      { title: '접이식 우산', description: '☔ 갑작스런 소나기 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '시티패스/교통패스', description: '🚇 대중교통 패스 사전 구매 권장', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '해외여행보험', description: '🏥 의료비 매우 비쌈, 필수 가입', baseQuantity: 1, unit: '개' },
      { title: '목베개', description: '✈️ 장거리 비행 필수템', baseQuantity: 1, unit: '개', multiplier: 1 },
    ]
  },
  // === 아시아 여행 ===
  {
    id: 'japan_travel',
    name: '일본 여행',
    description: '🗾 일본 특화 준비물 (현지 팁 포함)',
    category: '해외여행',
    peopleMultiplier: true,
    items: [
      { title: '여권', description: '90일 무비자, 유효기간 확인', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '엔화 현금', description: '💴 카드 안되는 곳 많음! 현금 필수 (총 5만엔 정도)', baseQuantity: 50000, unit: 'JPY' },
      { title: '포켓와이파이/eSIM', description: '📶 공공와이파이 제한적. 트리플 eSIM 할인 혜택 확인!', baseQuantity: 1, unit: '개' },
      { title: 'IC 카드', description: '🚇 스이카/파스모, 편의점 결제 가능', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '지진 앱', description: '📱 안전알리미, 일본 지진 알림 앱', baseQuantity: 1, unit: '개' },
      { title: '슬리퍼', description: '🥿 숙소/온천 입실 시 신발 벗음', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '타월', description: '🧖 온천 입장료에 타월 미포함', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '여행 필수 앱', description: '📱 트리플(일정), 파파고(번역), 구글맵', baseQuantity: 3, unit: '개' },
      { title: '현금 지갑', description: '👛 동전 많음, 동전지갑 필수', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '마스크', description: '😷 일본 마스크 문화, 예의', baseQuantity: 10, unit: '개' },
      { title: '편한 신발', description: '👟 많이 걸음, 신발 벗기 쉬운 것', baseQuantity: 1, unit: '켤레', multiplier: 1 },
    ]
  },
  // === 라이프 이벤트 ===
  {
    id: 'moving_prep',
    name: '이사 준비',
    description: '📦 이사 전후 필수 체크사항',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '이사업체 예약', description: '📞 최소 1주일 전 예약', baseQuantity: 1, unit: '업체' },
      { title: '박스/포장재', description: '📦 이삿짐 포장용 박스', baseQuantity: 20, unit: '개' },
      { title: '주소 변경 신고', description: '🏠 주민센터 전입신고', baseQuantity: 1, unit: '회' },
      { title: '인터넷 설치 예약', description: '🌐 입주 전 미리 예약', baseQuantity: 1, unit: '건' },
      { title: '가스 개통 신청', description: '🔥 도시가스 개통 예약', baseQuantity: 1, unit: '건' },
      { title: '전기 개통 신청', description: '⚡ 한전 전기 개통', baseQuantity: 1, unit: '건' },
      { title: '수도 개통 신청', description: '💧 상수도 개통 신청', baseQuantity: 1, unit: '건' },
      { title: '택배 주소 변경', description: '📮 쇼핑몰 배송지 변경', baseQuantity: 1, unit: '회' },
      { title: '은행 주소 변경', description: '🏛️ 주거래 은행 주소 변경', baseQuantity: 1, unit: '회' },
      { title: '청소용품', description: '🧽 입주 청소용 세제', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'wedding_prep',
    name: '결혼 준비',
    description: '💒 결혼 준비 필수 체크리스트',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '웨딩홀 예약', description: '🏛️ 6개월~1년 전 예약', baseQuantity: 1, unit: '곳' },
      { title: '웨딩드레스', description: '👰 드레스 시착 및 예약', baseQuantity: 1, unit: '벌' },
      { title: '신랑 예복', description: '🤵 턱시도/정장 맞춤', baseQuantity: 1, unit: '벌' },
      { title: '스튜디오 예약', description: '📸 웨딩촬영 스튜디오', baseQuantity: 1, unit: '곳' },
      { title: '메이크업 예약', description: '💄 본식 당일 메이크업', baseQuantity: 1, unit: '건' },
      { title: '청첩장 제작', description: '💌 하객 수에 맞춰 제작', baseQuantity: 100, unit: '장' },
      { title: '신혼여행 예약', description: '✈️ 허니문 항공+숙박', baseQuantity: 1, unit: '패키지' },
      { title: '예단/예물 준비', description: '💍 반지, 예단 준비', baseQuantity: 1, unit: '세트' },
      { title: '신부가방', description: '👜 한국 전통 결혼 문화, 신부 용돈 가방', baseQuantity: 1, unit: '개' },
      { title: '폐백 준비물', description: '🥜 대추, 밤 등 폐백 용품', baseQuantity: 1, unit: '세트' },
      { title: '하객 리스트', description: '📋 초대할 하객 명단', baseQuantity: 1, unit: '개' },
      { title: '혼인신고서', description: '📄 구청/주민센터 제출', baseQuantity: 1, unit: '통' },
    ]
  },
  // === 한국 특화 템플릿 ===
  {
    id: 'csat_exam',
    name: '수능 준비',
    description: '📝 수능 당일 필수 준비물',
    category: '학습',
    peopleMultiplier: false,
    items: [
      { title: '수험표', description: '📄 절대 필수! 복사본도 준비', baseQuantity: 2, unit: '매' },
      { title: '신분증', description: '🆔 주민등록증/학생증', baseQuantity: 1, unit: '개' },
      { title: '컴퓨터용 사인펜', description: '✏️ 검은색, 0.5mm', baseQuantity: 3, unit: '개' },
      { title: '연필', description: '✏️ 2B 연필 (샤프 금지)', baseQuantity: 5, unit: '개' },
      { title: '지우개', description: '🧽 깨끗한 지우개', baseQuantity: 2, unit: '개' },
      { title: '시계', description: '⏰ 아날로그 시계 (디지털 불가)', baseQuantity: 1, unit: '개' },
      { title: '휴대용 연필깎이', description: '✂️ 소음 적은 것', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '😷 개인 방역용', baseQuantity: 2, unit: '개' },
      { title: '초콜릿', description: '🍫 당분 보충용 (시끄럽지 않은 것)', baseQuantity: 2, unit: '개' },
      { title: '물', description: '💧 생수 (라벨 제거)', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'job_interview_korea',
    name: '한국 취업 면접',
    description: '👔 한국 기업 면접 특화 준비물',
    category: '업무',
    peopleMultiplier: false,
    items: [
      { title: '정장', description: '👔 네이비/차콜 정장 (다림질 필수)', baseQuantity: 1, unit: '벌' },
      { title: '구두', description: '👞 검은색 정장 구두 (광택)', baseQuantity: 1, unit: '켤레' },
      { title: '이력서', description: '📄 한국형 이력서 (사진 부착)', baseQuantity: 5, unit: '부' },
      { title: '자기소개서', description: '📋 회사별 맞춤 작성', baseQuantity: 3, unit: '부' },
      { title: '졸업증명서', description: '🎓 원본 + 복사본', baseQuantity: 2, unit: '부' },
      { title: '성적증명서', description: '📊 대학 성적표', baseQuantity: 2, unit: '부' },
      { title: '자격증 사본', description: '🏆 토익, 컴활 등', baseQuantity: 3, unit: '부' },
      { title: '증명사진', description: '📸 여분 (3x4cm)', baseQuantity: 5, unit: '매' },
      { title: '펜', description: '🖊️ 검은색 볼펜', baseQuantity: 2, unit: '개' },
      { title: '손수건', description: '🤧 긴장 시 땀 닦기용', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'korean_festival',
    name: '한국 축제 (벚꽃, 불꽃축제)',
    description: '🌸 한국 봄가을 축제 준비물',
    category: '문화',
    peopleMultiplier: true,
    items: [
      { title: '돗자리', description: '🏞️ 방수 돗자리 (앉을 자리 확보)', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '🍪 김밥, 과자 등', baseQuantity: 3, unit: '개', multiplier: 1 },
      { title: '음료', description: '🥤 시원한 음료', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '휴지', description: '🧻 물티슈 + 휴지', baseQuantity: 3, unit: '팩' },
      { title: '쓰레기봉투', description: '🗑️ 뒷정리용', baseQuantity: 3, unit: '개' },
      { title: '카메라/핸드폰', description: '📱 인생샷 촬영용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '보조배터리', description: '🔋 사진 많이 찍을 예정', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '얇은 외투', description: '🧥 저녁 기온 하락 대비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '방석/쿠션', description: '🪑 장시간 앉기 편한', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '선크림', description: '☀️ 야외 활동용', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'korean_hiking_mountain',
    name: '한국 산 등산 (북한산, 설악산)',
    description: '⛰️ 한국 명산 등반 준비물',
    category: '아웃도어', 
    peopleMultiplier: true,
    items: [
      { title: '등산화', description: '👟 발목 보호 등산화', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '등산복', description: '👕 속건성 소재', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '백팩', description: '🎒 20-30L 등산용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '물', description: '💧 충분한 수분 (500ml x 3)', baseQuantity: 1.5, unit: 'L', multiplier: 1 },
      { title: '김밥', description: '🍙 한국 등산 필수 도시락', baseQuantity: 1, unit: '줄', multiplier: 1 },
      { title: '막걸리', description: '🍶 정상 인증용 (선택사항)', baseQuantity: 1, unit: '병' },
      { title: '컵라면', description: '🍜 산장/대피소용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '등산스틱', description: '🦯 무릎 보호용', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '헤드랜턴', description: '🔦 일찍 어두워지는 계절', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '구급약', description: '🩹 밴드, 파스 등', baseQuantity: 1, unit: '세트' },
    ]
  },

  // === 2024년 인기 실용적 템플릿 9개 ===
  {
    id: 'business_trip',
    name: '출장 준비',
    description: '💼 직장인 출장 완벽 준비',
    category: '업무',
    peopleMultiplier: false,
    items: [
      { title: '노트북+충전기', description: '🔥꿀팁: 어댑터까지 챙기기', baseQuantity: 1, unit: '세트' },
      { title: '정장+넥타이', description: '회의용 정장 (다림질 필수)', baseQuantity: 2, unit: '벌' },
      { title: '구두+정장화', description: '편한 정장화 (오래 걸을 예정)', baseQuantity: 1, unit: '켤레' },
      { title: '출장 서류', description: '명함, 계약서, 프레젠테이션', baseQuantity: 1, unit: '세트' },
      { title: '휴대폰 충전기', description: '무선충전기 + 케이블', baseQuantity: 1, unit: '세트' },
      { title: '세면도구', description: '여행용 미니 세트', baseQuantity: 1, unit: '세트' },
      { title: '교통비+법인카드', description: '🔥꿀팁: 영수증 보관용 파일', baseQuantity: 1, unit: '세트' },
      { title: '비즈니스 가방', description: '노트북 수납 가능한 가방', baseQuantity: 1, unit: '개' },
      { title: '출장 일정표', description: '미팅 시간, 장소 정리', baseQuantity: 1, unit: '개' },
      { title: '간편 약품', description: '소화제, 두통약 등', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'hospital_admission',
    name: '병원 입원 준비',
    description: '🏥 입원 생활 필수품',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '입원 서류', description: '보험증, 신분증, 진료의뢰서', baseQuantity: 1, unit: '세트' },
      { title: '세면도구', description: '칫솔, 치약, 비누, 수건', baseQuantity: 1, unit: '세트' },
      { title: '입원복+속옷', description: '🔥꿀팁: 앞트임 편한 옷', baseQuantity: 3, unit: '벌' },
      { title: '슬리퍼', description: '병원 내 이동용', baseQuantity: 1, unit: '켤레' },
      { title: '휴지', description: '화장지, 물티슈', baseQuantity: 3, unit: '팩' },
      { title: '개인 물품', description: '안경, 보청기, 틀니 등', baseQuantity: 1, unit: '세트' },
      { title: '휴대폰 충전기', description: '긴 케이블 충전기', baseQuantity: 1, unit: '개' },
      { title: '휴대폰 거치대', description: '🔥꿀팁: 침상에서 영상시청용', baseQuantity: 1, unit: '개' },
      { title: '독서대', description: '🔥꿀팁: 누워서 책/태블릿 사용', baseQuantity: 1, unit: '개' },
      { title: '간식', description: '죽, 미음, 부드러운 음식', baseQuantity: 3, unit: '개' },
      { title: '현금', description: '병원 내 소액 결제용', baseQuantity: 50000, unit: '원' },
    ]
  },
  {
    id: 'newborn_prep',
    name: '신생아 준비물',
    description: '👶 신생아 맞이 필수품',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '기저귀', description: '신생아용 (하루 10-12개)', baseQuantity: 100, unit: '개' },
      { title: '젖병+젖꼭지', description: '🔥꿀팁: 다양한 브랜드로 준비', baseQuantity: 4, unit: '개' },
      { title: '분유', description: '초기 분유 (모유 보완용)', baseQuantity: 2, unit: '통' },
      { title: '아기옷', description: '신생아용 내의, 우주복', baseQuantity: 10, unit: '벌' },
      { title: '포대기+속싸개', description: '아기 포근하게 감쌀 용도', baseQuantity: 3, unit: '개' },
      { title: '카시트', description: '🔥꿀팁: 퇴원 시 법적 필수', baseQuantity: 1, unit: '개' },
      { title: '유모차', description: '신생아용 완전 눕는 유모차', baseQuantity: 1, unit: '개' },
      { title: '아기 목욕용품', description: '베이비 샴푸, 로션', baseQuantity: 1, unit: '세트' },
      { title: '아기침대+이불', description: '안전한 아기침대', baseQuantity: 1, unit: '세트' },
      { title: '체온계', description: '귀 체온계 (빠른 측정)', baseQuantity: 1, unit: '개' },
      { title: '손목쿠션', description: '🔥꿀팁: 수유시 팔 받침용 (엄마 필수템)', baseQuantity: 2, unit: '개' },
      { title: '유축기', description: '🔥꿀팁: 모유 보관용, 초기 젖몸살 완화', baseQuantity: 1, unit: '개' },
      { title: '기저귀 교환매트', description: '🔥꿀팁: 외출시 어디든 기저귀 갈 수 있음', baseQuantity: 1, unit: '개' },
      { title: '아기용 가습기', description: '🔥꿀팁: 신생아 호흡기 보호 필수', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'moving_checklist',
    name: '이사 준비',
    description: '📦 이사 전후 체크리스트',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '이사업체 예약', description: '📞 최소 1주일 전 예약', baseQuantity: 1, unit: '업체' },
      { title: '박스+포장재', description: '이삿짐 포장용 박스', baseQuantity: 30, unit: '개' },
      { title: '주소변경 신고', description: '🔥꿀팁: 주민센터 전입신고', baseQuantity: 1, unit: '회' },
      { title: '인터넷 설치 예약', description: '🌐 입주 전 미리 예약', baseQuantity: 1, unit: '건' },
      { title: '가스 개통 신청', description: '🔥 도시가스 개통 예약', baseQuantity: 1, unit: '건' },
      { title: '전기 개통 신청', description: '⚡ 한전 전기 개통', baseQuantity: 1, unit: '건' },
      { title: '수도 개통 신청', description: '💧 상수도 개통 신청', baseQuantity: 1, unit: '건' },
      { title: '택배 주소 변경', description: '📮 쇼핑몰 배송지 변경', baseQuantity: 1, unit: '회' },
      { title: '은행 주소 변경', description: '🏛️ 주거래 은행 주소 변경', baseQuantity: 1, unit: '회' },
      { title: '청소용품', description: '🧽 입주 청소용 세제', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'university_dorm',
    name: '대학교 기숙사',
    description: '🏫 기숙사 입주 준비물',
    category: '공부',
    peopleMultiplier: false,
    items: [
      { title: '침구세트', description: '이불, 베개, 시트', baseQuantity: 1, unit: '세트' },
      { title: '세탁용품', description: '세제, 섬유유연제, 빨래바구니', baseQuantity: 1, unit: '세트' },
      { title: '개인 수건', description: '목욕 수건, 세수 수건', baseQuantity: 3, unit: '개' },
      { title: '학용품', description: '📚 노트, 펜, 형광펜 등', baseQuantity: 1, unit: '세트' },
      { title: '노트북+충전기', description: '💻 수업/과제용', baseQuantity: 1, unit: '세트' },
      { title: '옷걸이', description: '🔥꿀팁: 기숙사 옷장용', baseQuantity: 20, unit: '개' },
      { title: '슬리퍼+실내화', description: '기숙사 내부용', baseQuantity: 2, unit: '켤레' },
      { title: '개인 식기', description: '컵, 그릇 (기숙사 규정 확인)', baseQuantity: 1, unit: '세트' },
      { title: '상비약', description: '감기약, 소화제, 두통약', baseQuantity: 1, unit: '세트' },
      { title: '간식+생필품', description: '🍪 야식용 + 화장지 등', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'honeymoon',
    name: '신혼여행',
    description: '✈️💕 신혼여행 특별 준비',
    category: '여행',
    peopleMultiplier: true,
    items: [
      { title: '여권+비자', description: '유효기간 6개월 이상', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '커플룩', description: '💑 기념사진용 매칭 의상', baseQuantity: 3, unit: '벌' },
      { title: '카메라+셀카봉', description: '📸 인생샷 촬영용', baseQuantity: 1, unit: '세트' },
      { title: '웨딩링 보관함', description: '💍 안전한 액세서리 케이스', baseQuantity: 1, unit: '개' },
      { title: '해외여행보험', description: '🏥 신혼여행 전용 보험', baseQuantity: 1, unit: '건' },
      { title: '현지 화폐', description: '💰 팁용 + 소액 결제용', baseQuantity: 500, unit: 'USD' },
      { title: '로맨틱 소품', description: '🌹 프로포즈 기념품 등', baseQuantity: 3, unit: '개' },
      { title: '여행 플래너', description: '📅 일정표, 예약 확인서', baseQuantity: 1, unit: '권' },
      { title: '휴대용 와이파이', description: '📶 해외 인터넷', baseQuantity: 1, unit: '개' },
      { title: '선물용 쇼핑백', description: '🎁 현지 기념품 구매용', baseQuantity: 3, unit: '개' },
    ]
  },
  {
    id: 'festival_concert',
    name: '페스티벌/콘서트',
    description: '🎵 음악 페스티벌/콘서트 준비',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '티켓', description: '🎫 모바일 티켓 + 신분증', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '보조배터리', description: '🔋 20000mAh 이상 대용량', baseQuantity: 1, unit: '개' },
      { title: '귀마개', description: '🔥꿀팁: 큰 소리 청력 보호용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '물병+간식', description: '💧 수분 보충 + 에너지 간식', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '편한 신발', description: '👟 오래 서있기 편한 운동화', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '쿨토시+모자', description: '☀️ 야외 페스티벌 필수', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '돗자리+방석', description: '🏞️ 앉을 자리 확보용', baseQuantity: 1, unit: '개' },
      { title: '현금', description: '💰 굿즈 구매용 (총 10만원 정도)', baseQuantity: 100000, unit: '원' },
      { title: '젖은 물티슈', description: '🧻 손 씻기 어려운 환경', baseQuantity: 3, unit: '팩' },
      { title: '비상 연락처', description: '📞 일행과 헤어졌을 때 대비', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'ski_snowboard',
    name: '스키/보드',
    description: '⛷️ 겨울 스포츠 완벽 준비',
    category: '운동',
    peopleMultiplier: true,
    items: [
      { title: '스키복/보드복', description: '🏂 방수, 방풍 전용복', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '고글+헬멧', description: '🥽 눈 보호 + 안전 장비', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '스키/보드 장비', description: '⛷️ 렌탈 예약 or 개인 장비', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '리프트권', description: '🎿 온라인 사전 구매 할인', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '방한 장갑', description: '🧤 방수 스키 전용 장갑', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '목워머+장목양말', description: '🧣 체온 보온용', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '핫팩', description: '🔥 손난로, 발난로', baseQuantity: 10, unit: '개' },
      { title: '선크림', description: '☀️ 설원 반사광 자외선 차단', baseQuantity: 1, unit: '개' },
      { title: '응급약품', description: '🩹 타박상, 염좌 대비', baseQuantity: 1, unit: '세트' },
      { title: '여벌 옷', description: '👕 젖은 옷 갈아입을 용도', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '척추 보호대', description: '🔥꿀팁: 초보자 필수! 넘어질 때 척추 보호', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '무릎 보호대', description: '🔥꿀팁: 부상 예방의 핵심, 특히 보드 초보자', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '엉덩이 패드', description: '🔥꿀팁: 보드 초심자 절대 필수템 (통증 완화)', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '손목 보호대', description: '🔥꿀팁: 넘어질 때 손목 골절 방지 필수', baseQuantity: 1, unit: '켤레', multiplier: 1 },
      { title: '발가락 핫팩', description: '🔥꿀팁: 일반 핫팩과 별도, 동상 방지용', baseQuantity: 5, unit: '개' },
      { title: '고글 김서림 방지제', description: '🔥꿀팁: 시야 확보 필수템', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'exam_prep',
    name: '시험 준비',
    description: '📚 각종 시험 대비 필수품',
    category: '공부',
    peopleMultiplier: false,
    items: [
      { title: '수험표', description: '📄 절대 필수! 복사본도 준비', baseQuantity: 2, unit: '매' },
      { title: '신분증', description: '🆔 주민등록증/학생증', baseQuantity: 1, unit: '개' },
      { title: '필기구', description: '✏️ 볼펜, 연필, 샤프 등', baseQuantity: 5, unit: '개' },
      { title: '지우개', description: '🧽 깨끗한 지우개', baseQuantity: 2, unit: '개' },
      { title: '시계', description: '⏰ 조용한 시계 (스마트워치 불가)', baseQuantity: 1, unit: '개' },
      { title: '계산기', description: '🔢 허용 기종 확인 필수', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '😷 개인 방역용', baseQuantity: 2, unit: '개' },
      { title: '초콜릿', description: '🍫 당분 보충용 (조용한 것)', baseQuantity: 2, unit: '개' },
      { title: '물', description: '💧 생수 (라벨 제거)', baseQuantity: 1, unit: '개' },
      { title: '휴대용 방석', description: '🔥꿀팁: 딱딱한 의자 대비', baseQuantity: 1, unit: '개' },
    ]
  },

  // === 추가 14개 전문분야 템플릿 ===
  {
    id: 'fishing_trip',
    name: '낚시',
    description: '🎣 바다/민물 낚시 준비',
    category: '아웃도어',
    peopleMultiplier: true,
    items: [
      { title: '낚싟대+릴', description: '🎣 대상어에 맞는 낚싟대', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '미끼+바늘', description: '🐛 여러 크기 준비', baseQuantity: 1, unit: '세트' },
      { title: '쿨러+얼음', description: '🧊 잡은 물고기 보관용', baseQuantity: 1, unit: '개' },
      { title: '낚시 의상', description: '👕 방수 재킷+바지', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '선글라스+모자', description: '☀️ 자외선 차단', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '간편식', description: '🍜 캬밥, 라면 등', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '낚시용 의자', description: '🪑 접이식 의자', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '헤드랜턴', description: '🔦 새벽/야간 낚시용', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '낚시 허가증', description: '📄 지역별 필요 시 준비', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '응급약품', description: '🩹 냄시바늘 상처 대비', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'job_change_prep',
    name: '이직/퇴사 준비',
    description: '💼 직장 이동 준비사항',
    category: '업무',
    peopleMultiplier: false,
    items: [
      { title: '사직서', description: '📄 사직 2주일 전 제출', baseQuantity: 1, unit: '부' },
      { title: '업무인수인계서', description: '📅 후임자에게 전달할 내용', baseQuantity: 1, unit: '부' },
      { title: '개인물품 정리', description: '📦 사무용품 vs 개인용품 분리', baseQuantity: 1, unit: '박스' },
      { title: '경력증명서', description: '📜 재직 증명용', baseQuantity: 3, unit: '부' },
      { title: '퀀직금 정산', description: '💰 연차, 퀀직금 계산', baseQuantity: 1, unit: '건' },
      { title: '건강보험 전환', description: '🏥 직장보험 → 지역보험', baseQuantity: 1, unit: '건' },
      { title: '동료 연락처', description: '📞 개인 연락처 백업', baseQuantity: 1, unit: '개' },
      { title: '회사 자료 반납', description: '📊 회사 기밀자료 반납', baseQuantity: 1, unit: '박스' },
      { title: '새 직장 준비', description: '👔 첫출근 의상 준비', baseQuantity: 1, unit: '벌' },
      { title: '영수증 백업', description: '📁 세무서류 보관', baseQuantity: 1, unit: '파일' },
    ]
  },
  {
    id: 'baby_shower',
    name: '베이비샤워',
    description: '🎉 임신 축하 파티',
    category: '생활',
    peopleMultiplier: true,
    items: [
      { title: '초대장', description: '💌 임신축하 초대장', baseQuantity: 20, unit: '장' },
      { title: '배너+풍선', description: '🎈 아기 테마 장식', baseQuantity: 1, unit: '세트' },
      { title: '아기용품 선물', description: '🎁 기저귀, 오일, 아기복', baseQuantity: 3, unit: '개', multiplier: 1 },
      { title: '케이크+디저트', description: '🎂 임신축하 케이크', baseQuantity: 1, unit: '개' },
      { title: '음료+간식', description: '🧊 노카페인 음료', baseQuantity: 10, unit: '개' },
      { title: '게임 준비', description: '🎲 베이비샤워 게임', baseQuantity: 3, unit: '개' },
      { title: '카메라', description: '📸 기념사진 촬영용', baseQuantity: 1, unit: '개' },
      { title: '좋은말 카드', description: '📝 임신부에게 격려 메시지', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '일회용품', description: '🍽️ 일회용 식기', baseQuantity: 20, unit: '세트' },
      { title: '음악 플레이리스트', description: '🎵 편안한 배경음악', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'pet_travel',
    name: '반려동물 여행',
    description: '🐶 애완동물과 여행',
    category: '여행',
    peopleMultiplier: false,
    items: [
      { title: '여행용 캐리어', description: '🎒 차량/비행기용', baseQuantity: 1, unit: '개' },
      { title: '동물등록증+예방접종 기록', description: '📄 여행지 필수서류', baseQuantity: 1, unit: '세트' },
      { title: '사료+물그릇', description: '🍽️ 여행지에서 사용', baseQuantity: 2, unit: '세트' },
      { title: '개 목줄+하네스', description: '🧽 안전한 산책용', baseQuantity: 1, unit: '세트' },
      { title: '배변봉투+티슈', description: '📦 청소용품', baseQuantity: 10, unit: '개' },
      { title: '동물용 섘이드', description: '🧼 스트레스 완화용', baseQuantity: 1, unit: '개' },
      { title: '반려동물 보험', description: '🏥 여행 중 응급상황 대비', baseQuantity: 1, unit: '건' },
      { title: '동물병원 연락처', description: '🏥 여행지 동물병원 정보', baseQuantity: 1, unit: '개' },
      { title: '좋아하는 장난감', description: '🧿 스트레스 완화용', baseQuantity: 2, unit: '개' },
      { title: '여분 비닐봉지', description: '📦 비상상황 대비', baseQuantity: 5, unit: '장' },
    ]
  },
  {
    id: 'home_party',
    name: '집들이',
    description: '🎉 친구들과 집에서 파티',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '음료', description: '🍺 맥주, 소주, 뜬코올 음료', baseQuantity: 3, unit: '병', multiplier: 1 },
      { title: '안주+옥납', description: '🍖 간단한 안주류', baseQuantity: 5, unit: '종류' },
      { title: '치킨+피자', description: '🍕 배달 주문 or 직접 요리', baseQuantity: 2, unit: '판', multiplier: 1 },
      { title: '음향장비', description: '🔊 블루투스 스피커', baseQuantity: 1, unit: '개' },
      { title: '게임+보드게임', description: '🎲 한 번에 즈길 수 있는 게임', baseQuantity: 3, unit: '개' },
      { title: '일회용 컵+접시', description: '🥂 설거지 편의용', baseQuantity: 10, unit: '개' },
      { title: '얼음+쿨러', description: '🧊 음료 시원하게', baseQuantity: 2, unit: 'kg' },
      { title: '쓰레기믑투', description: '🗑️ 정리용', baseQuantity: 5, unit: '개' },
      { title: '공기청정기', description: '🌬️ 담배연기 제거', baseQuantity: 1, unit: '개' },
      { title: '비상 연락처', description: '📞 너무 시끌 때 대비', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'car_maintenance',
    name: '자동차 정비',
    description: '🚗 자동차 관리 체크리스트',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '엔진오일 점검', description: '🔧 5000-10000km마다', baseQuantity: 1, unit: '회' },
      { title: '타이어 점검', description: '😏 마모도, 공기압 체크', baseQuantity: 4, unit: '개' },
      { title: '비상도구', description: '🔧 육각렉치, 점퍼케이블', baseQuantity: 1, unit: '세트' },
      { title: '차량용 소화기', description: '🧨 법적 의무사항', baseQuantity: 1, unit: '개' },
      { title: '세차용품', description: '🧽 카샴푸, 웩스, 타웤클리너', baseQuantity: 1, unit: '세트' },
      { title: '배터리 체크', description: '🔋 전압 측정기', baseQuantity: 1, unit: '개' },
      { title: '냉각수 점검', description: '💧 냉각수 누수 체크', baseQuantity: 1, unit: '회' },
      { title: '브레이크패드', description: '🛑 제동력 점검', baseQuantity: 1, unit: '세트' },
      { title: '에어컨 필터', description: '🌬️ 공기청정 필터', baseQuantity: 1, unit: '개' },
      { title: '보험증+등록증', description: '📄 자동차 서류 확인', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'gardening',
    name: '원예/가드닝',
    description: '🌱 집에서 식물 기르기',
    category: '여가',
    peopleMultiplier: false,
    items: [
      { title: '원예용 흙', description: '🌱 배수가 잘 되는 표준 혼합토', baseQuantity: 10, unit: 'L' },
      { title: '씨앗+모종', description: '🌱 계절에 맞는 식물', baseQuantity: 5, unit: '종류' },
      { title: '화분+플랜터', description: '🏺 식물 크기에 맞는 화분', baseQuantity: 5, unit: '개' },
      { title: '원예도구', description: '🔧 삽, 갈퀴, 가위 등', baseQuantity: 1, unit: '세트' },
      { title: '물뿔리개', description: '💧 식물 물주기용', baseQuantity: 1, unit: '개' },
      { title: '비료+영양제', description: '🌱 식물 성장 도움', baseQuantity: 3, unit: '병' },
      { title: '방충망+방충제', description: '🐛 해충 방지', baseQuantity: 1, unit: '세트' },
      { title: '원예용 장갑', description: '🧤 손 보호용', baseQuantity: 1, unit: '켤레' },
      { title: '식물 이름표', description: '🏷️ 식물 관리 용이', baseQuantity: 10, unit: '개' },
      { title: '원예 작업대', description: '🪑 편안한 작업 공간', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'cherry_blossom_date',
    name: '벚꽃 데이트',
    description: '🌸 봄 벚꽃 데이트 준비',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '돗자리+방석', description: '🌸 벚꽃 나무 아래서 피크닉', baseQuantity: 1, unit: '개' },
      { title: '카메라+셀카봉', description: '📸 벚꽃 인생샷 촬영용', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '따뜻한 음료', description: '☕ 커피, 따뜻한 차 등', baseQuantity: 2, unit: '개', multiplier: 1 },
      { title: '공원 간식', description: '🍪 김밥, 샌드위치, 과자', baseQuantity: 3, unit: '개' },
      { title: '하루종일 데이트 코스', description: '🗺️ 벚꽃 명소 + 카페 + 저녁', baseQuantity: 1, unit: '코스' },
      { title: '벚꽃 예보 체크', description: '🌸 개화 시기 미리 확인', baseQuantity: 1, unit: '회' },
      { title: '봄 의상', description: '👗 계절에 맞는 예쁜 옷', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '외투+시원음료', description: '🧊 봄바람 쌀쌀하지만 갈증 대비', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '합류 장소', description: '📍 벚꽃 명소 및 만남 장소 정보', baseQuantity: 1, unit: '개' },
      { title: '대중교통 이용법', description: '🚌 인파 많은 봄계절 대비', baseQuantity: 1, unit: '개' },
      { title: '벚꽃잎 받기 게임 준비', description: '🌸 떨어지는 벚꽃잎 손으로 받기 (로맨틱 포인트)', baseQuantity: 1, unit: '회' },
      { title: '\"꽃보다 당신이 예뻐\" 멘트', description: '😍 준비된 로맨틱 멘트 (부끄럽지만 효과적)', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'pet_walk',
    name: '반려동물 산책',
    description: '🐕 강아지 산책 준비',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '목줄+하네스', description: '🦽 안전한 산책용', baseQuantity: 1, unit: '세트' },
      { title: '배변봉투+티슈', description: '📦 배변 처리용', baseQuantity: 5, unit: '개' },
      { title: '강아지 간식', description: '🦴 보상용 간식', baseQuantity: 3, unit: '개' },
      { title: '휴대용 물그릇', description: '🍽️ 산책 중 물 주기용', baseQuantity: 1, unit: '개' },
      { title: '신분인식표', description: '🏷️ 기본 정보 담긴 인식표', baseQuantity: 1, unit: '개' },
      { title: '응급연락처', description: '📞 병원 연락처 메모', baseQuantity: 1, unit: '개' },
      { title: '스마트폰 충전기', description: '🔋 놀이터사진 + 비상시 연락', baseQuantity: 1, unit: '개' },
      { title: '마스크', description: '😷 개인 방역용', baseQuantity: 2, unit: '개' },
      { title: '손 소독제', description: '🧼 변 치운 후 손 소독', baseQuantity: 1, unit: '개' },
      { title: '휴대용 수건', description: '🧽 때 묻은 강아지 닦아주기', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'class_reunion',
    name: '동창회/동창회',
    description: '🎆 오랜만에 만나는 동창모임',
    category: '여가',
    peopleMultiplier: false,
    items: [
      { title: '정장류 의상', description: '👔 깨끗한 정장 또는 에레간트 캐주얼', baseQuantity: 1, unit: '벌' },
      { title: '명함+연락처', description: '👤 현재 직업 정보 및 연락처', baseQuantity: 20, unit: '장' },
      { title: '선물', description: '🎁 은사님께 드릴 선물', baseQuantity: 1, unit: '개' },
      { title: '카메라', description: '📸 단체사진 촬영용', baseQuantity: 1, unit: '개' },
      { title: '예비 현금', description: '💰 회비, 2차 비용 등', baseQuantity: 150000, unit: '원' },
      { title: '사연 이야기', description: '💬 근황 대화 주제 준비', baseQuantity: 5, unit: '개' },
      { title: '개인사 준비', description: '🎤 간단한 인사말 준비', baseQuantity: 1, unit: '개' },
      { title: '대중교통 이용', description: '🚌 음주 후 안전 귀가', baseQuantity: 1, unit: '회' },
      { title: '연락처 업데이트', description: '📞 만난 친구들 연락처 백업', baseQuantity: 1, unit: '회' },
      { title: '사진 인화', description: '🖼️ 학생 때 사진 또는 인증샷', baseQuantity: 3, unit: '장' },
      { title: '\"그때 그 시절\" 추억팩', description: '📼 옛날 사진, 편지, 급식표 등 (눈물 주의)', baseQuantity: 1, unit: '세트' },
      { title: '\"나 진짜 바뀌었지?\" 자신감', description: '💅 현재 모습에 대한 자부심 충전 완료', baseQuantity: 1, unit: '회' },
    ]
  },
  {
    id: 'volunteering',
    name: '자원봉사',
    description: '🤝 자원봉사 활동 준비',
    category: '생활',
    peopleMultiplier: false,
    items: [
      { title: '자원봉사 신청서', description: '📄 사전 등록 또는 신청', baseQuantity: 1, unit: '부' },
      { title: '신분증 사본', description: '🆔 본인확인용', baseQuantity: 1, unit: '부' },
      { title: '편안한 작업복', description: '👕 더러워도 되는 옷', baseQuantity: 1, unit: '벌' },
      { title: '작업용 장갑', description: '🧤 방수 작업용 장갑', baseQuantity: 1, unit: '켤레' },
      { title: '개인 수건+물티슈', description: '🧽 개인 위생용품', baseQuantity: 1, unit: '세트' },
      { title: '간식+음료', description: '🍪 매대 또는 봉사자와 나눠먹기', baseQuantity: 3, unit: '개' },
      { title: '교통비', description: '🚌 봉사지역 이동비', baseQuantity: 10000, unit: '원' },
      { title: '카메라', description: '📸 봉사활동 기록용', baseQuantity: 1, unit: '개' },
      { title: '명함', description: '👤 다른 봉사자와 네트워킹', baseQuantity: 10, unit: '장' },
      { title: '예비 연락처', description: '📞 상황 종료 후 연락체계', baseQuantity: 1, unit: '개' },
    ]
  },
  {
    id: 'photo_studio',
    name: '사진관 촬영',
    description: '📸 프로필 or 가족사진 촬영',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '촬영 의상', description: '👕 연출의도에 맞는 옷 3병', baseQuantity: 3, unit: '벌', multiplier: 1 },
      { title: '액세서리', description: '💍 귀걱이, 목걸이, 시계 등', baseQuantity: 3, unit: '세트', multiplier: 1 },
      { title: '헤어 스타일링', description: '💇 미리 원하는 헤어스타일 결정', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '메이크업 도구', description: '💄 간단한 리터칭용', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '예약 확인서', description: '📅 촬영 시간, 장소 확인', baseQuantity: 1, unit: '건' },
      { title: '여벌 옷', description: '👚 촬영 전 옷 더러워졌을 때', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '신발', description: '👠 의상에 맞는 신발 2켤레', baseQuantity: 2, unit: '켤레', multiplier: 1 },
      { title: '결제 카드', description: '💳 추가 옵션 결제용', baseQuantity: 1, unit: '개' },
      { title: '배경 희망사항', description: '📋 원하는 컷삷 또는 배경', baseQuantity: 1, unit: '개' },
      { title: '포즈 연습', description: '🤳 미리 연습해본 포즈', baseQuantity: 5, unit: '개', multiplier: 1 },
    ]
  },
  {
    id: 'late_night_study',
    name: '밤샘 공부',
    description: '🌙 24시 시험공부 준비',
    category: '공부',
    peopleMultiplier: false,
    items: [
      { title: '카페인 음료', description: '☕ 커피, 에너지드링크 등', baseQuantity: 3, unit: '개' },
      { title: '눈 보호 안경', description: '👓 블루라이트 차단 안경', baseQuantity: 1, unit: '개' },
      { title: '데스크 램프', description: '🔦 눈 피로 예방용', baseQuantity: 1, unit: '개' },
      { title: '가벼운 야식', description: '🍪 견과류, 에너지바', baseQuantity: 5, unit: '개' },
      { title: '헤드폰+이어플러그', description: '🎧 집중력 향상용', baseQuantity: 1, unit: '개' },
      { title: '방석+담요', description: '🛏 오래 앉기 편하게', baseQuantity: 1, unit: '세트' },
      { title: '휴대용 충전기', description: '🔋 도서관에서 충전', baseQuantity: 1, unit: '개' },
      { title: '미니 수건', description: '🧽 잘 때 세면용', baseQuantity: 1, unit: '개' },
      { title: '막차 시간 주의', description: '🚂 심야 버스 시간 미리 체크', baseQuantity: 1, unit: '회' },
      { title: '비상연락처', description: '📞 심야시간 가족 연락용', baseQuantity: 1, unit: '개' },
      { title: '\"내일부터 열심히 할 거야\" 다짐', description: '😅 매번 하는 다짐이지만 이번엔 진짜...', baseQuantity: 1, unit: '회' },
      { title: '새벽 3시 후회타임 대비책', description: '🤦‍♂️ \"왜 미리 안했지?\" 자책 방지용 멘탈케어', baseQuantity: 1, unit: '세트' },
    ]
  },
  {
    id: 'bridal_shower',
    name: '브라이덜샤워',
    description: '👰 결혼 축하 파티 준비',
    category: '여가',
    peopleMultiplier: true,
    items: [
      { title: '레터링 풍선', description: '🎈 "Bride to be" 또는 "Bridal Shower" 문구', baseQuantity: 1, unit: '세트' },
      { title: '화려한 부케', description: '🌺 신부 소울템! 생화로 화려한 컬러', baseQuantity: 1, unit: '개' },
      { title: '화관+꽃팔찌', description: '🌸 흰드레스와 조화, 인증샷 필수템', baseQuantity: 1, unit: '세트', multiplier: 1 },
      { title: '신부 드레스', description: '👗 화이트 드레스 (대여 가능)', baseQuantity: 1, unit: '벌' },
      { title: '친구들 드레스', description: '👗 통일된 드레스코드 (예: 올블랙)', baseQuantity: 1, unit: '벌', multiplier: 1 },
      { title: '티아라+면사포', description: '👑 브라이덜샤워 전용 액세서리', baseQuantity: 1, unit: '세트' },
      { title: '색안경+소품', description: '🕶️ 재미있는 인증샷용 포토프롭', baseQuantity: 5, unit: '개' },
      { title: '웨딩슈즈', description: '👠 신부만의 화이트 구두로 차별화', baseQuantity: 1, unit: '켤레' },
      { title: '축하 케이크', description: '🎂 파티 메인! 직접제작 or 모형케이크', baseQuantity: 1, unit: '개' },
      { title: '디저트+음료', description: '🥂 파티용 간단한 핑거푸드', baseQuantity: 1, unit: '세트' },
      { title: '카메라+삼각대', description: '📸 단체사진 및 인증샷 촬영용', baseQuantity: 1, unit: '세트' },
      { title: '축하 선물', description: '🎁 신부에게 줄 결혼축하 선물', baseQuantity: 1, unit: '개', multiplier: 1 },
      { title: '플레이리스트', description: '🎵 파티 분위기 BGM 준비', baseQuantity: 1, unit: '개' },
      { title: '포토존 세팅', description: '🔥꿀팁: 풍선 많을수록 사진 잘 나옴', baseQuantity: 1, unit: '세트' },
    ]
  }
]

export function getTemplate(templateId: string): SituationTemplate | undefined {
  return SITUATION_TEMPLATES.find(template => template.id === templateId)
}

export function calculateQuantity(item: { baseQuantity?: number; multiplier?: number }, peopleCount: number = 1): number {
  if (!item.multiplier) return item.baseQuantity || 1
  return (item.baseQuantity || 1) * Math.max(1, peopleCount)
}

export function generateChecklistFromTemplate(
  templateId: string, 
  peopleCount: number = 1
): { items: { title: string; description?: string; quantity: number; unit?: string; order: number }[] } | null {
  const template = getTemplate(templateId)
  if (!template) return null

  const items = template.items.map((item, index) => ({
    title: item.title,
    description: item.description,
    quantity: calculateQuantity(item, template.peopleMultiplier ? peopleCount : 1),
    unit: item.unit,
    isCompleted: false,
    order: index,
  }))

  return { items }
}